#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "RELAY_POSTFIX_MASTER_CONFIG" "/etc/postfix/master.cf"
bf-env "RELAY_POSTFIX_MAIN_CONFIG" "/etc/postfix/main.cf"
bf-env "RELAY_POSTFIX_GENERIC_MAP" "/etc/postfix/generic"
bf-env "RELAY_POSTFIX_VIRTUAL_MAP" "/etc/postfix/virtual"
