#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate Clamsmtp configuration file.
#======================================================================================================================

# ensure all required environment variables are set

# generate config from the templates
bf-debug "Generating ${RELAY_CLAMSMTP_CONFIG}."
esh -o ${RELAY_CLAMSMTP_CONFIG} \
    ${BF_TEMPLATES}/clamsmtp.conf.esh
